spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://192.168.2.10:5432/champagne
    username: postgres
    password: sa
    driverClassName: org.postgresql.Driver
